// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"time"
)

type Userinfo struct {
	ID       int64
	Email    string
	FullName string
	Created  time.Time
}
