// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"quickscopedev/database"
)

type NewIntegration struct {
	TeamID          int64                    `json:"teamId"`
	IntegrationName database.IntegrationType `json:"integrationName"`
}

type NewMonitor struct {
	TeamID      int64  `json:"teamId"`
	MonitorName string `json:"monitorName"`
}
